apiVersion: v1
kind: Service
metadata:
  name: www
  labels:
    app: www
    app.kubernetes.io/instance: www
    app.kubernetes.io/name: www
    app.kubernetes.io/managed-by: tangerine-k8s-cluster
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: sminnee
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: www
